/d435i:
  camera:
    ros__parameters:
      serial_no: 026222250386 # d455
      align_depth: false
      enable_pointcloud: true
      dense_pointcloud: true
      color0:
        enabled: true
        resolution: [640,480]
        fps: 30
      depth0:
        enabled: true
        resolution: [640,480]
        fps: 30
      infra1:
        enabled: true
        resolution: [640,480]
        fps: 30
      infra2:
        enabled: true
        resolution: [640,480]
        fps: 30
      accel0:
        enabled: true
      gyro0:
        enabled: true